version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: sui-fantasy-league-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sui_fantasy_league
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 